import type { Locale } from "@/i18n/locales";

export interface LegalSection {
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
}

export interface LegalDocument {
  title: string;
  updatedLabel: string;
  intro: string;
  sections: LegalSection[];
}

export const LEGAL_LAST_UPDATED = "2026-09-24";
export const SUPPORT_EMAIL = "support@zyonix.pro";

const TERMS: Record<Locale, LegalDocument> = {
  en: {
    title: "Terms of Use",
    updatedLabel: "Last updated",
    intro:
      "These Terms of Use govern your access to and use of Zyonix, an AI-assisted content studio for Christian creators and churches (the \"Service\"). By creating an account or using the Service you agree to these Terms. If you do not agree, please do not use the Service.",
    sections: [
      {
        heading: "1. The Service",
        paragraphs: [
          "Zyonix provides tools to create Bible art, social media posts, devotionals, sermon and message outlines, short videos and quizzes, to keep a personal prayer journal and Bible reading progress, to chat with an AI-based spiritual companion, and — on team plans — to manage a church workspace (members, contact list, events, email communications and a simple finance ledger).",
          "We may add, change or remove features over time. We will try to give notice of changes that materially affect paying customers.",
        ],
      },
      {
        heading: "2. Eligibility and accounts",
        bullets: [
          "You must be at least 16 years old. If you are under the age of majority where you live, you may use the Service only with the permission of a parent or legal guardian.",
          "You are responsible for the accuracy of your account information, for keeping your credentials secure, and for everything that happens under your account.",
          "One person per account. Team plans let the team owner invite additional members; the owner is responsible for the people they invite.",
        ],
      },
      {
        heading: "3. Plans, billing and credits",
        paragraphs: [
          "Paid plans are subscriptions that renew automatically each billing period (monthly or annual) until cancelled. Payments are processed by our payment provider, Hotmart; we never see or store your full card details.",
          "Each plan includes an allowance of credits for AI generations that is refreshed every billing cycle. Unused credits do not roll over to the next cycle. Feature availability and allowances depend on your plan and are shown on the pricing page.",
          "You can cancel at any time through Hotmart or by contacting us; access continues until the end of the period you already paid for. Refunds, including any guarantee period, follow the terms shown at checkout and Hotmart's policies, plus any refund right you have under mandatory consumer law where you live.",
          "If a payment fails, we may suspend paid features until the payment is resolved.",
        ],
      },
      {
        heading: "4. AI-generated content",
        bullets: [
          "Images, text, videos and other outputs are generated by artificial intelligence and may be inaccurate, incomplete, or similar to other content. Review everything before you publish or rely on it.",
          "Scripture references and theological content are provided as an aid, not as authoritative teaching. Zyonix is not a substitute for your pastor, church leadership or your own study.",
          "As between you and us, you may use the outputs you generate for your own personal, ministry and commercial purposes, subject to these Terms and to the terms of our AI providers. We do not guarantee that outputs are free of third-party rights, so you are responsible for how you use them.",
          "You are responsible for the prompts and materials you submit, and you confirm you have the right to use them.",
        ],
      },
      {
        heading: "5. Spiritual chat is not professional care",
        paragraphs: [
          "The spiritual chat offers Bible-based reflection and prayer support. It is not therapy, counseling, medical, legal or financial advice, and it is not a substitute for professional care or emergency services.",
          "If you are in crisis or thinking about harming yourself or others, contact your local emergency number right away (988 in the United States) or a trusted person near you.",
        ],
      },
      {
        heading: "6. Acceptable use",
        paragraphs: ["You agree not to:"],
        bullets: [
          "break the law, or use the Service to create content that is hateful, harassing, sexually explicit, deceptive, or that infringes anyone's rights;",
          "send spam or unsolicited messages, or add email addresses to your church contact list without the permission of the people concerned;",
          "attempt to bypass usage limits, credits, rate limits or security controls, probe or scan the Service for vulnerabilities, or access data that is not yours;",
          "reverse engineer, resell or provide the Service to third parties except as your plan allows;",
          "use automated means (bots, scrapers) to access the Service, or interfere with its operation.",
        ],
      },
      {
        heading: "7. Church workspace",
        paragraphs: [
          "If you use the team features, you are responsible for the contacts you add, for having the right to email them, and for the content of every message sent from your workspace. Messages are sent from our sending domain; they include a footer identifying your church and how to opt out, which you may not remove.",
          "The finance ledger is a simple record-keeping tool. It is not accounting, tax or legal advice and does not replace professional bookkeeping.",
        ],
      },
      {
        heading: "8. Your content and our rights",
        paragraphs: [
          "You keep ownership of the content you put into the Service. You grant us a limited license to host, process and display it solely to operate the Service for you (including sending it to our AI and infrastructure providers as described in our Privacy Policy).",
          "The Service itself — software, design, branding and templates — belongs to us and our licensors. These Terms do not grant you any rights to it except the right to use the Service as described here.",
        ],
      },
      {
        heading: "9. Suspension and termination",
        paragraphs: [
          "You may stop using the Service and delete your account at any time from Settings. We may suspend or terminate accounts that violate these Terms, put the Service or other users at risk, or are used for fraud or abuse. Where reasonable, we will tell you why.",
        ],
      },
      {
        heading: "10. Disclaimers and limitation of liability",
        paragraphs: [
          "The Service is provided \"as is\" and \"as available\". To the fullest extent permitted by law, we disclaim all warranties, and we are not liable for indirect, incidental or consequential damages, loss of profits, or loss of data arising from your use of the Service. Our total liability for any claim is limited to the amount you paid us in the 12 months before the claim arose.",
          "Nothing in these Terms limits rights or liability that cannot be limited under applicable law, including mandatory consumer protections.",
        ],
      },
      {
        heading: "11. Changes to these Terms",
        paragraphs: [
          "We may update these Terms from time to time. If a change is material we will notify you (for example by email or in the app) before it takes effect. Continuing to use the Service after that means you accept the updated Terms.",
        ],
      },
      {
        heading: "12. Governing law",
        paragraphs: [
          "These Terms are governed by the laws of the Federative Republic of Brazil, without regard to conflict-of-law rules. If you are a consumer, you also keep the protection of the mandatory consumer laws of the place where you live.",
        ],
      },
      {
        heading: "13. Contact",
        paragraphs: [`Questions about these Terms? Write to ${SUPPORT_EMAIL}.`],
      },
    ],
  },
  es: {
    title: "Términos de Uso",
    updatedLabel: "Última actualización",
    intro:
      "Estos Términos de Uso regulan tu acceso y uso de Zyonix, un estudio de contenido asistido por IA para creadores cristianos e iglesias (el \"Servicio\"). Al crear una cuenta o usar el Servicio aceptas estos Términos. Si no estás de acuerdo, por favor no uses el Servicio.",
    sections: [
      {
        heading: "1. El Servicio",
        paragraphs: [
          "Zyonix ofrece herramientas para crear arte bíblico, publicaciones para redes sociales, devocionales, bosquejos de mensajes y sermones, videos cortos y cuestionarios, llevar un diario de oración y el progreso de lectura bíblica, conversar con un acompañante espiritual basado en IA y, en los planes de equipo, gestionar un espacio de iglesia (miembros, lista de contactos, eventos, comunicaciones por correo y un registro financiero simple).",
          "Podemos agregar, cambiar o retirar funciones con el tiempo. Intentaremos avisar de los cambios que afecten de forma importante a los clientes de pago.",
        ],
      },
      {
        heading: "2. Elegibilidad y cuentas",
        bullets: [
          "Debes tener al menos 16 años. Si eres menor de edad según la ley de tu país, solo puedes usar el Servicio con permiso de tu padre, madre o tutor legal.",
          "Eres responsable de que los datos de tu cuenta sean correctos, de mantener seguras tus credenciales y de todo lo que ocurra en tu cuenta.",
          "Una persona por cuenta. Los planes de equipo permiten que el propietario invite a más miembros; el propietario es responsable de las personas que invita.",
        ],
      },
      {
        heading: "3. Planes, cobros y créditos",
        paragraphs: [
          "Los planes de pago son suscripciones que se renuevan automáticamente cada período de facturación (mensual o anual) hasta que se cancelen. Los pagos los procesa nuestro proveedor de pagos, Hotmart; nunca vemos ni almacenamos los datos completos de tu tarjeta.",
          "Cada plan incluye una cantidad de créditos para generaciones con IA que se renueva en cada ciclo de facturación. Los créditos no usados no se acumulan para el ciclo siguiente. Las funciones y las cantidades dependen de tu plan y se muestran en la página de precios.",
          "Puedes cancelar en cualquier momento a través de Hotmart o escribiéndonos; el acceso continúa hasta el final del período ya pagado. Los reembolsos, incluido cualquier período de garantía, siguen las condiciones mostradas al pagar y las políticas de Hotmart, además de cualquier derecho de reembolso que tengas según la ley de consumo obligatoria de tu país.",
          "Si un pago falla, podemos suspender las funciones de pago hasta que se resuelva.",
        ],
      },
      {
        heading: "4. Contenido generado por IA",
        bullets: [
          "Las imágenes, textos, videos y demás resultados los genera inteligencia artificial y pueden ser inexactos, incompletos o parecidos a otros contenidos. Revisa todo antes de publicarlo o basarte en ello.",
          "Las referencias bíblicas y el contenido teológico son una ayuda, no una enseñanza autorizada. Zyonix no sustituye a tu pastor, al liderazgo de tu iglesia ni a tu propio estudio.",
          "Entre tú y nosotros, puedes usar los resultados que generes para fines personales, de ministerio y comerciales, sujeto a estos Términos y a los términos de nuestros proveedores de IA. No garantizamos que los resultados estén libres de derechos de terceros, por lo que eres responsable de cómo los uses.",
          "Eres responsable de las instrucciones y materiales que envías, y confirmas que tienes derecho a usarlos.",
        ],
      },
      {
        heading: "5. El chat espiritual no es atención profesional",
        paragraphs: [
          "El chat espiritual ofrece reflexión basada en la Biblia y apoyo en oración. No es terapia, consejería, ni asesoría médica, legal o financiera, y no sustituye la atención profesional ni los servicios de emergencia.",
          "Si estás en crisis o piensas en hacerte daño a ti o a otros, llama de inmediato a tu número local de emergencias (988 en Estados Unidos) o acude a una persona de confianza cercana.",
        ],
      },
      {
        heading: "6. Uso aceptable",
        paragraphs: ["Te comprometes a no:"],
        bullets: [
          "infringir la ley, ni usar el Servicio para crear contenido que sea de odio, acoso, sexualmente explícito, engañoso o que vulnere derechos de otros;",
          "enviar spam o mensajes no solicitados, ni agregar correos a tu lista de contactos de iglesia sin permiso de las personas correspondientes;",
          "intentar eludir límites de uso, créditos, límites de frecuencia o controles de seguridad, ni explorar el Servicio en busca de vulnerabilidades, ni acceder a datos que no son tuyos;",
          "aplicar ingeniería inversa, revender u ofrecer el Servicio a terceros, salvo lo que permita tu plan;",
          "usar medios automatizados (bots, scrapers) para acceder al Servicio o interferir con su funcionamiento.",
        ],
      },
      {
        heading: "7. Espacio de iglesia",
        paragraphs: [
          "Si usas las funciones de equipo, eres responsable de los contactos que agregues, de tener derecho a escribirles y del contenido de cada mensaje enviado desde tu espacio. Los mensajes se envían desde nuestro dominio e incluyen un pie que identifica a tu iglesia y cómo dejar de recibirlos, el cual no puedes eliminar.",
          "El registro financiero es una herramienta simple de anotación. No es asesoría contable, fiscal ni legal y no reemplaza una contabilidad profesional.",
        ],
      },
      {
        heading: "8. Tu contenido y nuestros derechos",
        paragraphs: [
          "Conservas la propiedad del contenido que introduces en el Servicio. Nos otorgas una licencia limitada para alojarlo, procesarlo y mostrarlo únicamente para operar el Servicio para ti (incluido enviarlo a nuestros proveedores de IA e infraestructura, como se describe en la Política de Privacidad).",
          "El Servicio en sí (software, diseño, marca y plantillas) pertenece a nosotros y a nuestros licenciantes. Estos Términos no te dan ningún derecho sobre él, salvo el de usar el Servicio como aquí se describe.",
        ],
      },
      {
        heading: "9. Suspensión y terminación",
        paragraphs: [
          "Puedes dejar de usar el Servicio y eliminar tu cuenta en cualquier momento desde Configuración. Podemos suspender o cerrar cuentas que incumplan estos Términos, pongan en riesgo el Servicio u otros usuarios, o se usen para fraude o abuso. Cuando sea razonable, te explicaremos el motivo.",
        ],
      },
      {
        heading: "10. Exclusiones y limitación de responsabilidad",
        paragraphs: [
          "El Servicio se ofrece \"tal cual\" y \"según disponibilidad\". En la máxima medida permitida por la ley, excluimos toda garantía y no respondemos por daños indirectos, incidentales o consecuentes, lucro cesante o pérdida de datos derivados del uso del Servicio. Nuestra responsabilidad total por cualquier reclamación se limita al importe que nos pagaste en los 12 meses anteriores.",
          "Nada en estos Términos limita derechos o responsabilidades que no puedan limitarse según la ley aplicable, incluidas las protecciones obligatorias al consumidor.",
        ],
      },
      {
        heading: "11. Cambios en estos Términos",
        paragraphs: [
          "Podemos actualizar estos Términos. Si el cambio es importante te avisaremos (por ejemplo, por correo o en la aplicación) antes de que entre en vigor. Seguir usando el Servicio después significa que aceptas los Términos actualizados.",
        ],
      },
      {
        heading: "12. Ley aplicable",
        paragraphs: [
          "Estos Términos se rigen por las leyes de la República Federativa de Brasil, sin considerar sus normas de conflicto de leyes. Si eres consumidor, conservas además la protección de las leyes de consumo obligatorias del lugar donde vives.",
        ],
      },
      {
        heading: "13. Contacto",
        paragraphs: [`¿Preguntas sobre estos Términos? Escribe a ${SUPPORT_EMAIL}.`],
      },
    ],
  },
};

const PRIVACY: Record<Locale, LegalDocument> = {
  en: {
    title: "Privacy Policy",
    updatedLabel: "Last updated",
    intro:
      "This policy explains what personal data Zyonix collects, why, who we share it with, and the choices you have. We designed the Service to collect only what it needs. Because prayer requests, devotional notes and spiritual conversations can reveal religious beliefs — a sensitive category of data in many countries — we treat them with particular care.",
    sections: [
      {
        heading: "1. Who is responsible",
        paragraphs: [
          `Zyonix is the controller of the personal data described here. You can reach us at ${SUPPORT_EMAIL} for anything related to your data.`,
          "If you use the church workspace and add other people's names and emails, you decide why and how that data is used; in that case you are the controller and we process it on your behalf.",
        ],
      },
      {
        heading: "2. Data we collect",
        bullets: [
          "Account data: your name, email address and password (stored only as a secure hash), or your Google profile basics if you sign in with Google.",
          "Content you create and store: generated images, posts, devotional notes, message outlines, videos, prayer requests, Bible favorites and reading progress, quiz results, and badges.",
          "Photos you upload for poster templates (for example a speaker photo): the photo is sent to OpenAI to create your poster and is not kept by us. The finished poster, which may show the likeness of the person in the photo, is stored in your account. Only upload photos of people who have agreed to it.",
          "Spiritual chat: your conversations, and — when crisis-related language is detected — a safety flag linked to your account for human review. It is never used to penalize you.",
          "Subscription data: your plan, billing cycle, status and credit balance, and the identifiers Hotmart sends us for your purchase (transaction and subscriber codes, buyer name and email). We do not receive or store your card number.",
          "Church workspace data (if you use it): team members, contact names and emails, events, sent-message history and finance entries.",
          "Technical data: IP address, device and browser information and request logs generated by our hosting and security providers, and usage counters used for rate limiting and abuse prevention.",
          "Advertising measurement data (only if you accept optional cookies): which of our public pages you viewed, whether you clicked a checkout button and whether you created an account, together with a cookie identifier. This is collected by the Meta Pixel and is never taken from inside the app itself once you have a plan.",
        ],
      },
      {
        heading: "3. Why we use it and our legal bases",
        bullets: [
          "To provide the Service you asked for — creating content, running your account, applying your plan and credits (performance of a contract).",
          "To process payments and manage subscriptions, and to keep records we are legally required to keep (contract and legal obligation).",
          "To send service emails: purchase confirmation, account and password emails, and — only if you keep the setting on — the daily devotional reminder (contract and legitimate interest; you can turn the reminder off in Settings).",
          "To keep the Service safe: fraud and abuse prevention, rate limiting, crisis-safety review (legitimate interest and, for safety flags, vital interests).",
          "For sensitive data such as religious beliefs, we process it only to provide the features you use, on the basis of your explicit consent when you choose to enter that content.",
          "To measure and improve our advertising through the Meta Pixel — only with your consent, which you can withdraw at any time from \"Cookie preferences\" in the site footer.",
          "To send you at most one reminder email if you create an account but haven't chosen a plan within a few days. It carries an unsubscribe link, and we stop as soon as you use it (legitimate interest; you can object at any time).",
        ],
      },
      {
        heading: "4. Who we share data with",
        paragraphs: [
          "We do not sell your personal data, and what you create or write in your account is never used for advertising. We share data only with service providers that help us run Zyonix, under contracts that limit how they may use it:",
        ],
        bullets: [
          "Supabase — database, authentication and file storage.",
          "Netlify — website and application hosting.",
          "OpenAI — generating text, images and moderating chat messages. Content you submit for generation is sent to OpenAI's API; under OpenAI's API terms, data sent through the API is not used to train its models by default.",
          "Runway — generating videos from the prompts you provide.",
          "Resend — sending transactional and church emails.",
          "Hotmart — payment processing and subscription management.",
          "Cloudflare (Turnstile) — bot protection on sign-in and sign-up forms.",
          "Google — only if you choose to sign in with Google.",
          "Meta (Facebook and Instagram) — only if you accept optional cookies: the Meta Pixel tells Meta about your visit to our public pages so we can measure our ads and show them to relevant people. Meta handles that data under its own privacy policy.",
        ],
      },
      {
        heading: "5. International transfers",
        paragraphs: [
          "Our providers operate in several countries, including the United States. Where the law requires it, we rely on appropriate safeguards (such as standard contractual clauses) for those transfers.",
        ],
      },
      {
        heading: "6. Cookies",
        paragraphs: [
          "Essential cookies: the sign-in session cookie and a language-preference cookie. The bot-protection widget from Cloudflare may also set its own technical cookies to work. These do not need your consent.",
          "Optional cookies: only if you click \"Accept\" in the cookie banner, we load the Meta Pixel on our public pages (home, terms, privacy, sign-up and welcome) and on the plan-selection page right after sign-up. It sets cookies such as _fbp and _fbc and sends Meta information about your visit and actions, like clicking a checkout button or creating an account. We do not load it inside the app once you have a plan, on sign-in or on password-reset pages. If you arrive from one of our ads, the ad's click identifier is kept in your browser for that visit and only passed to Meta if you accept.",
          "You can decline, or change your mind at any time, with \"Cookie preferences\" in the site footer. Declining does not affect how Zyonix works.",
        ],
      },
      {
        heading: "7. How long we keep data",
        paragraphs: [
          "We keep your data while your account is active. When you delete your account in Settings, your profile, content, prayer journal, chat history and stored files are permanently deleted from our systems right away; residual copies in backups are overwritten in the normal backup cycle. Payment records held by Hotmart are kept by them as required by law.",
        ],
      },
      {
        heading: "8. Your rights",
        paragraphs: [
          "Depending on where you live (including under Brazil's LGPD and the EU/UK GDPR), you have the right to access, correct, delete and port your data, to object to or restrict certain processing, to withdraw consent, and to lodge a complaint with your data-protection authority (in Brazil, the ANPD).",
          `In Settings you can download a copy of your data and delete your account yourself. For anything else, write to ${SUPPORT_EMAIL} and we will respond within a reasonable time, and in any case within the period required by law.`,
        ],
      },
      {
        heading: "9. Security",
        paragraphs: [
          "We protect your data with encryption in transit, row-level access controls so users can only read their own data, bot and abuse protection, and restricted access to production systems. No system is perfectly secure; if a breach affecting your data occurs we will notify you and the authorities as the law requires.",
          "Administrative access is limited and recorded. Our small authorized team can see account and subscription information (such as your email, plan and credit balance) to give you support and to handle your data requests. We do not read the content of your prayer journal, notes or spiritual chat. The only exception is a message that our system automatically flags as a possible crisis, which may be opened by an authorized person for safety review. Every administrative access or action is written to an audit log that cannot be altered, protected by two-factor authentication.",
        ],
      },
      {
        heading: "10. Children",
        paragraphs: [
          "Zyonix is not directed to children under 16 and we do not knowingly collect their data. If you believe a child has given us personal data, contact us and we will delete it.",
        ],
      },
      {
        heading: "11. Changes to this policy",
        paragraphs: [
          "We may update this policy. We will post the new version here with a new date and, for material changes, notify you before they take effect.",
        ],
      },
      {
        heading: "12. Contact",
        paragraphs: [`Privacy questions or requests, and our data-protection contact under the LGPD: ${SUPPORT_EMAIL}.`],
      },
    ],
  },
  es: {
    title: "Política de Privacidad",
    updatedLabel: "Última actualización",
    intro:
      "Esta política explica qué datos personales recopila Zyonix, para qué, con quién los compartimos y qué opciones tienes. Diseñamos el Servicio para recopilar solo lo necesario. Como las peticiones de oración, las notas devocionales y las conversaciones espirituales pueden revelar creencias religiosas —una categoría sensible de datos en muchos países—, las tratamos con especial cuidado.",
    sections: [
      {
        heading: "1. Quién es responsable",
        paragraphs: [
          `Zyonix es el responsable del tratamiento de los datos personales descritos aquí. Puedes escribirnos a ${SUPPORT_EMAIL} para cualquier asunto sobre tus datos.`,
          "Si usas el espacio de iglesia y agregas nombres y correos de otras personas, tú decides para qué y cómo se usan esos datos; en ese caso tú eres el responsable y nosotros los tratamos por tu cuenta.",
        ],
      },
      {
        heading: "2. Datos que recopilamos",
        bullets: [
          "Datos de cuenta: tu nombre, correo y contraseña (almacenada solo como un hash seguro), o los datos básicos de tu perfil de Google si inicias sesión con Google.",
          "Contenido que creas y guardas: imágenes generadas, publicaciones, notas devocionales, bosquejos de mensajes, videos, peticiones de oración, favoritos bíblicos y progreso de lectura, resultados de cuestionarios e insignias.",
          "Fotos que subes para las plantillas de carteles (por ejemplo, la foto de un orador): la foto se envía a OpenAI para crear tu cartel y no la conservamos. El cartel terminado, que puede mostrar el rostro de la persona de la foto, se guarda en tu cuenta. Sube solo fotos de personas que estén de acuerdo.",
          "Chat espiritual: tus conversaciones y, cuando se detecta lenguaje relacionado con una crisis, una alerta de seguridad vinculada a tu cuenta para revisión humana. Nunca se usa para penalizarte.",
          "Datos de suscripción: tu plan, ciclo de facturación, estado y saldo de créditos, y los identificadores que Hotmart nos envía sobre tu compra (códigos de transacción y suscriptor, nombre y correo del comprador). No recibimos ni almacenamos el número de tu tarjeta.",
          "Datos del espacio de iglesia (si lo usas): miembros del equipo, nombres y correos de contactos, eventos, historial de mensajes enviados y movimientos financieros.",
          "Datos técnicos: dirección IP, información del dispositivo y del navegador y registros de solicitudes generados por nuestros proveedores de alojamiento y seguridad, y contadores de uso para limitar la frecuencia y prevenir abusos.",
          "Datos de medición publicitaria (solo si aceptas las cookies opcionales): qué páginas públicas viste, si hiciste clic en un botón de pago y si creaste una cuenta, junto con un identificador de cookie. Los recopila el Píxel de Meta y nunca se toman desde dentro de la aplicación una vez que tienes un plan.",
        ],
      },
      {
        heading: "3. Para qué los usamos y bases legales",
        bullets: [
          "Para prestar el Servicio que solicitaste: crear contenido, gestionar tu cuenta, aplicar tu plan y créditos (ejecución de un contrato).",
          "Para procesar pagos y gestionar suscripciones, y conservar los registros que la ley nos exige (contrato y obligación legal).",
          "Para enviar correos de servicio: confirmación de compra, correos de cuenta y contraseña y —solo si mantienes la opción activa— el recordatorio devocional diario (contrato e interés legítimo; puedes desactivarlo en Configuración).",
          "Para mantener seguro el Servicio: prevención de fraude y abuso, límites de frecuencia y revisión de seguridad ante crisis (interés legítimo y, en las alertas de seguridad, intereses vitales).",
          "Los datos sensibles, como las creencias religiosas, los tratamos solo para ofrecer las funciones que usas, con base en tu consentimiento explícito cuando decides introducir ese contenido.",
          "Para medir y mejorar nuestra publicidad mediante el Píxel de Meta, solo con tu consentimiento, que puedes retirar en cualquier momento desde \"Preferencias de cookies\" en el pie del sitio.",
          "Para enviarte como máximo un correo recordatorio si creas una cuenta pero no eliges un plan en unos días. Incluye un enlace para darte de baja y dejamos de enviarlo en cuanto lo usas (interés legítimo; puedes oponerte en cualquier momento).",
        ],
      },
      {
        heading: "4. Con quién compartimos datos",
        paragraphs: [
          "No vendemos tus datos personales, y lo que creas o escribes en tu cuenta nunca se usa para publicidad. Solo compartimos datos con proveedores que nos ayudan a operar Zyonix, mediante contratos que limitan el uso que pueden darles:",
        ],
        bullets: [
          "Supabase: base de datos, autenticación y almacenamiento de archivos.",
          "Netlify: alojamiento del sitio y la aplicación.",
          "OpenAI: generación de texto e imágenes y moderación de mensajes del chat. El contenido que envías para generar se manda a la API de OpenAI; según los términos de la API de OpenAI, los datos enviados por la API no se usan por defecto para entrenar sus modelos.",
          "Runway: generación de videos a partir de las instrucciones que proporcionas.",
          "Resend: envío de correos transaccionales y de iglesia.",
          "Hotmart: procesamiento de pagos y gestión de suscripciones.",
          "Cloudflare (Turnstile): protección contra bots en los formularios de inicio de sesión y registro.",
          "Google: solo si eliges iniciar sesión con Google.",
          "Meta (Facebook e Instagram): solo si aceptas las cookies opcionales; el Píxel de Meta le informa de tu visita a nuestras páginas públicas para que podamos medir nuestros anuncios y mostrarlos a personas relevantes. Meta trata esos datos según su propia política de privacidad.",
        ],
      },
      {
        heading: "5. Transferencias internacionales",
        paragraphs: [
          "Nuestros proveedores operan en varios países, incluido Estados Unidos. Cuando la ley lo exige, nos apoyamos en garantías adecuadas (como cláusulas contractuales tipo) para esas transferencias.",
        ],
      },
      {
        heading: "6. Cookies",
        paragraphs: [
          "Cookies esenciales: la cookie de sesión de inicio de sesión y una cookie de preferencia de idioma. El widget de protección contra bots de Cloudflare también puede establecer sus propias cookies técnicas para funcionar. Estas no requieren tu consentimiento.",
          "Cookies opcionales: solo si pulsas \"Aceptar\" en el aviso de cookies, cargamos el Píxel de Meta en nuestras páginas públicas (inicio, términos, privacidad, registro y bienvenida) y en la página de elección de plan justo después del registro. Establece cookies como _fbp y _fbc y envía a Meta información sobre tu visita y tus acciones, como hacer clic en un botón de pago o crear una cuenta. No lo cargamos dentro de la aplicación una vez que tienes un plan, en el inicio de sesión ni en el restablecimiento de contraseña. Si llegas desde uno de nuestros anuncios, el identificador de clic del anuncio se guarda en tu navegador durante esa visita y solo se pasa a Meta si aceptas.",
          "Puedes rechazarlas, o cambiar de opinión en cualquier momento, con \"Preferencias de cookies\" en el pie del sitio. Rechazarlas no afecta al funcionamiento de Zyonix.",
        ],
      },
      {
        heading: "7. Cuánto tiempo conservamos los datos",
        paragraphs: [
          "Conservamos tus datos mientras tu cuenta esté activa. Cuando eliminas tu cuenta en Configuración, tu perfil, contenido, diario de oración, historial de chat y archivos almacenados se borran de forma permanente de nuestros sistemas de inmediato; las copias residuales en respaldos se sobrescriben en el ciclo normal de respaldo. Los registros de pago que conserva Hotmart los mantiene esa empresa según exige la ley.",
        ],
      },
      {
        heading: "8. Tus derechos",
        paragraphs: [
          "Según donde vivas (incluidas la LGPD de Brasil y el RGPD de la UE/Reino Unido), tienes derecho a acceder, corregir, eliminar y portar tus datos, a oponerte o limitar ciertos tratamientos, a retirar tu consentimiento y a presentar una reclamación ante tu autoridad de protección de datos (en Brasil, la ANPD).",
          `En Configuración puedes descargar una copia de tus datos y eliminar tu cuenta tú mismo. Para cualquier otra cosa, escribe a ${SUPPORT_EMAIL} y responderemos en un plazo razonable y, en todo caso, dentro del plazo que exija la ley.`,
        ],
      },
      {
        heading: "9. Seguridad",
        paragraphs: [
          "Protegemos tus datos con cifrado en tránsito, controles de acceso por fila para que cada usuario solo lea sus propios datos, protección contra bots y abusos, y acceso restringido a los sistemas de producción. Ningún sistema es perfectamente seguro; si ocurre una brecha que afecte tus datos te avisaremos a ti y a las autoridades como exige la ley.",
          "El acceso administrativo es limitado y queda registrado. Nuestro pequeño equipo autorizado puede ver información de la cuenta y la suscripción (como tu correo, plan y saldo de créditos) para darte soporte y atender tus solicitudes sobre datos. No leemos el contenido de tu diario de oración, tus notas ni el chat espiritual. La única excepción es un mensaje que nuestro sistema marca automáticamente como posible crisis, que una persona autorizada puede abrir para revisión de seguridad. Todo acceso o acción administrativa se guarda en un registro de auditoría que no puede alterarse, protegido con autenticación de dos factores.",
        ],
      },
      {
        heading: "10. Menores",
        paragraphs: [
          "Zyonix no está dirigido a menores de 16 años y no recopilamos sus datos a sabiendas. Si crees que un menor nos ha dado datos personales, contáctanos y los eliminaremos.",
        ],
      },
      {
        heading: "11. Cambios en esta política",
        paragraphs: [
          "Podemos actualizar esta política. Publicaremos aquí la nueva versión con una nueva fecha y, si el cambio es importante, te avisaremos antes de que entre en vigor.",
        ],
      },
      {
        heading: "12. Contacto",
        paragraphs: [`Preguntas o solicitudes de privacidad, y nuestro contacto de protección de datos según la LGPD: ${SUPPORT_EMAIL}.`],
      },
    ],
  },
};

export function getTerms(locale: Locale): LegalDocument {
  return TERMS[locale];
}

export function getPrivacy(locale: Locale): LegalDocument {
  return PRIVACY[locale];
}
